### ISSUE TITLE
404 - No route matches

### ISSUE THREAD

**Issue by ErikMartensson** [ChakreshwarSharma-BTC/github_commits#2]
I can't get this plugin to work, I only get a 404 error.
The plugin is placed in `redmine/plugins/github_commits` with the same permissions as the rest of my Redmine files.
The plugin is active and up to date according to the plugins list within Redmine.
I've run `bundle install` and `bundle exec rake redmine:plugins:migrate RAILS_ENV=production` after placing it in the plugins folder.

Redmine version: 3.3.2
Plugin version: 0.0.2

Have I missed some important step in the installation process or am I just stupid in some other way? I really don't see what I've could have missed.

Here's the log output after posting to the webhook from GitHub:
```
Started POST "/github_commits/create_comment" for 192.30.252.40 at 2017-03-27 11:13:07 +0200

ActionController::RoutingError (No route matches [POST] "/github_commits/create_comment"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by PaarthBarot** [comment]
@ErikMartensson I am using it with redmine `3.3.1` and working fine, can you just try to replicate this on a dev environment first? Also, Please check it in the routes first if its created or not. Once I will check this on `3.3.2`, shall update here.

__Update__

If you see the root, its `post 'github_commits/create_comment.json', to: 'github_commits#create_comment'`. It expects to be a json request, I think this might be the case. Let me see if I forgot to update the readme! :disappointed:

**Comment by PaarthBarot** [comment]
@ErikMartensson I have updated the `README` now, Please try updating the webhook URL in Github as `/github_commits/create_comment.json` and let me know if that works.

Thanks :+1:

**Comment by PaarthBarot** [comment]
@ErikMartensson Did my last comment work for you?
